title: The Sketching Developer
title_separator: "-"
description: "Sketching my way through developer topics"
baseurl: ""
url: ""
favicon: "/assets/images/logo.png"
avatar: "/assets/images/logo.png"
comments: false
atom_feed:
  path: # blank (default) uses feed.xml
twitter:
  username: flyingtophat
github:
  username: sketchingdev

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Site Author
author:
  name: "SketchingDev" # appears in the footer and atom feed

# Plugins
plugins:
  - jekyll-feed

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-feed

permalink: /blog/:title/
