# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Sketching Developer
title_separator: "-"
email: your-email@example.com
description: "Sketching my way through developer topics"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: flyingtophat
github_username:  sketchingdev
favicon: "/assets/images/bird.png"
avatar: "/assets/images/bird.png"
comments: false
atom_feed:
  path: # blank (default) uses feed.xml
twitter:
  username: flyingtophat

# Build settings
markdown: kramdown
theme: sparrow-jekyll-theme
plugins:
  - jekyll-feed

# Site Author
author:
  name: "FlyingTopHat" # appears in the footer and atom feed

# Plugins
plugins:
  - jekyll-feed

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-feed

permalink: /blog/:title/
